# Generated by Django 4.2.4 on 2023-09-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail_key',
            field=models.CharField(default=None, max_length=30, verbose_name='ключ'),
        ),
    ]