# Generated by Django 4.2.4 on 2023-09-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_mail_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail_key',
            field=models.CharField(default=None, max_length=30, verbose_name='key'),
        ),
    ]