# Generated by Django 4.2.4 on 2023-09-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='count_view',
            field=models.PositiveIntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]