# Generated by Django 4.2.4 on 2023-08-21 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('full_name', models.CharField(max_length=100, verbose_name='фио')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='SettingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.DateTimeField(verbose_name='время рассылки')),
                ('period', models.CharField(max_length=20, verbose_name='периодичность')),
                ('status', models.CharField(max_length=20, verbose_name='статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'настройка',
                'verbose_name_plural': 'настройки',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(default='no subject', verbose_name='тема')),
                ('text', models.TextField(verbose_name='текст')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.client', verbose_name='настройки')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_try', models.DateTimeField(verbose_name='время последний попытки')),
                ('status_try', models.CharField(max_length=50, verbose_name='статус')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='ответ')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.client', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]