# Generated by Django 4.2.4 on 2023-08-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmail',
            name='mailing_time',
            field=models.TimeField(verbose_name='время рассылки'),
        ),
    ]