# Generated by Django 4.2.4 on 2023-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_settingmail_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmail',
            name='period',
            field=models.PositiveIntegerField(default=1, verbose_name='периодичность'),
        ),
    ]