# Generated by Django 4.2.4 on 2023-08-22 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_alter_settingmail_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.mailing', verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.settingmail', verbose_name='настройки'),
        ),
    ]