# Generated by Django 4.2.4 on 2023-09-07 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_alter_log_mail_alter_mailing_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.settingmail', verbose_name='настройки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.settingmail', verbose_name='настройки'),
        ),
        migrations.AlterField(
            model_name='settingmail',
            name='period',
            field=models.PositiveIntegerField(choices=[(1, 'Раз в день'), (7, 'Раз в неделю'), (31, 'Раз в месяц')], verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='settingmail',
            name='status',
            field=models.CharField(choices=[('create', 'Создана'), ('start', 'Запущена'), ('finish', 'Закончена')], default='create', verbose_name='статус'),
        ),
    ]