# Generated by Django 4.2.4 on 2023-09-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_log_setting_alter_mailing_setting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmail',
            name='status',
            field=models.BooleanField(default=False, verbose_name='статус'),
        ),
    ]