# Generated by Django 4.2.4 on 2023-09-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_client_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmail',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.client', verbose_name='клиент'),
        ),
    ]